-- Oracle schema v2 for Identity Resolution Engine POC
-- Preserves existing schema file: sql/oracle_ire_schema.sql

CREATE TABLE source_systems (
  source_system_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_code VARCHAR2(100) NOT NULL UNIQUE,
  source_name VARCHAR2(200) NOT NULL,
  trust_level VARCHAR2(30) NOT NULL,
  is_internal NUMBER(1) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_source_systems_internal CHECK (is_internal IN (0,1)),
  CONSTRAINT ck_source_systems_trust CHECK (trust_level IN ('high','medium','low'))
);

CREATE TABLE source_records (
  source_record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system_id NUMBER NOT NULL,
  source_pk VARCHAR2(200) NOT NULL,
  raw_payload CLOB CHECK (raw_payload IS JSON),
  ingest_status VARCHAR2(30) DEFAULT 'ingested' NOT NULL,
  ingested_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  ingested_by VARCHAR2(200),
  CONSTRAINT fk_source_records_system FOREIGN KEY (source_system_id) REFERENCES source_systems(source_system_id),
  CONSTRAINT uq_source_record UNIQUE (source_system_id, source_pk)
);

CREATE TABLE normalized_identities (
  normalized_identity_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id NUMBER NOT NULL,
  normalized_name VARCHAR2(1000),
  normalized_email VARCHAR2(320),
  normalized_phone VARCHAR2(64),
  normalized_address VARCHAR2(2000),
  normalized_hkid VARCHAR2(64),
  normalized_emplid VARCHAR2(64),
  normalized_student_id VARCHAR2(64),
  normalized_alumni_id VARCHAR2(64),
  attributes_json CLOB CHECK (attributes_json IS JSON),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_norm_source_record FOREIGN KEY (source_record_id) REFERENCES source_records(source_record_id)
);

CREATE TABLE golden_records (
  golden_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_status VARCHAR2(30) DEFAULT 'active' NOT NULL,
  person_type VARCHAR2(50),
  canonical_name VARCHAR2(1000),
  canonical_email VARCHAR2(320),
  canonical_phone VARCHAR2(64),
  canonical_address VARCHAR2(2000),
  canonical_hkid VARCHAR2(64),
  canonical_emplid VARCHAR2(64),
  canonical_student_id VARCHAR2(64),
  canonical_alumni_id VARCHAR2(64),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_golden_status CHECK (person_status IN ('active','inactive','merged'))
);

CREATE TABLE golden_field_values (
  golden_field_value_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  golden_id NUMBER NOT NULL,
  field_name VARCHAR2(100) NOT NULL,
  field_value VARCHAR2(4000),
  source_record_id NUMBER,
  source_system_id NUMBER,
  survivorship_rule_code VARCHAR2(100),
  is_current NUMBER(1) DEFAULT 1 NOT NULL,
  evidence_json CLOB CHECK (evidence_json IS JSON),
  valid_from TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  valid_to TIMESTAMP,
  CONSTRAINT fk_gfv_golden FOREIGN KEY (golden_id) REFERENCES golden_records(golden_id),
  CONSTRAINT fk_gfv_source_record FOREIGN KEY (source_record_id) REFERENCES source_records(source_record_id),
  CONSTRAINT fk_gfv_source_system FOREIGN KEY (source_system_id) REFERENCES source_systems(source_system_id),
  CONSTRAINT ck_gfv_current CHECK (is_current IN (0,1))
);

CREATE TABLE record_links (
  record_link_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id NUMBER NOT NULL,
  golden_id NUMBER NOT NULL,
  link_status VARCHAR2(30) DEFAULT 'active' NOT NULL,
  link_method VARCHAR2(30) NOT NULL,
  confidence NUMBER(5,4),
  matched_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  evidence_json CLOB CHECK (evidence_json IS JSON),
  CONSTRAINT fk_record_links_source FOREIGN KEY (source_record_id) REFERENCES source_records(source_record_id),
  CONSTRAINT fk_record_links_golden FOREIGN KEY (golden_id) REFERENCES golden_records(golden_id),
  CONSTRAINT ck_record_link_status CHECK (link_status IN ('active','superseded','rejected')),
  CONSTRAINT ck_record_link_method CHECK (link_method IN ('deterministic','probabilistic','manual','rebatch'))
);

CREATE TABLE match_candidates (
  match_candidate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id NUMBER NOT NULL,
  golden_id NUMBER NOT NULL,
  candidate_rank NUMBER(6) NOT NULL,
  confidence NUMBER(5,4) NOT NULL,
  decision_hint VARCHAR2(40),
  blocked_reason VARCHAR2(200),
  summary_json CLOB CHECK (summary_json IS JSON),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_match_candidates_source FOREIGN KEY (source_record_id) REFERENCES source_records(source_record_id),
  CONSTRAINT fk_match_candidates_golden FOREIGN KEY (golden_id) REFERENCES golden_records(golden_id)
);

CREATE TABLE match_candidate_features (
  match_candidate_feature_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_candidate_id NUMBER NOT NULL,
  feature_type VARCHAR2(50) NOT NULL,
  field_name VARCHAR2(100),
  rule_code VARCHAR2(100),
  similarity_score NUMBER(5,4),
  weight NUMBER(10,6),
  weighted_score NUMBER(10,6),
  passed NUMBER(1) DEFAULT 0 NOT NULL,
  evidence_json CLOB CHECK (evidence_json IS JSON),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_mcf_candidate FOREIGN KEY (match_candidate_id) REFERENCES match_candidates(match_candidate_id),
  CONSTRAINT ck_mcf_passed CHECK (passed IN (0,1))
);

CREATE TABLE manual_review_tasks (
  task_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id NUMBER NOT NULL,
  task_status VARCHAR2(30) DEFAULT 'open' NOT NULL,
  review_reason VARCHAR2(200),
  recommended_action VARCHAR2(40),
  priority VARCHAR2(20) DEFAULT 'normal',
  assigned_to VARCHAR2(200),
  due_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  task_payload CLOB CHECK (task_payload IS JSON),
  CONSTRAINT fk_review_task_source FOREIGN KEY (source_record_id) REFERENCES source_records(source_record_id),
  CONSTRAINT ck_review_task_status CHECK (task_status IN ('open','in_progress','resolved','cancelled'))
);

CREATE TABLE manual_review_decisions (
  review_decision_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id NUMBER NOT NULL,
  selected_golden_id NUMBER,
  decision VARCHAR2(40) NOT NULL,
  reviewer VARCHAR2(200),
  rationale VARCHAR2(2000),
  decision_payload CLOB CHECK (decision_payload IS JSON),
  decided_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_review_decision_task FOREIGN KEY (task_id) REFERENCES manual_review_tasks(task_id),
  CONSTRAINT fk_review_decision_golden FOREIGN KEY (selected_golden_id) REFERENCES golden_records(golden_id),
  CONSTRAINT ck_review_decision CHECK (decision IN ('auto-merge','manual-merge','new-golden-record','reject','escalate'))
);

CREATE TABLE merge_history (
  merge_history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id NUMBER,
  from_golden_id NUMBER,
  to_golden_id NUMBER,
  event_type VARCHAR2(40) NOT NULL,
  event_by VARCHAR2(200),
  event_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  event_payload CLOB CHECK (event_payload IS JSON),
  CONSTRAINT fk_merge_history_source FOREIGN KEY (source_record_id) REFERENCES source_records(source_record_id),
  CONSTRAINT fk_merge_history_from_golden FOREIGN KEY (from_golden_id) REFERENCES golden_records(golden_id),
  CONSTRAINT fk_merge_history_to_golden FOREIGN KEY (to_golden_id) REFERENCES golden_records(golden_id)
);

CREATE TABLE matching_rules (
  rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_code VARCHAR2(100) NOT NULL UNIQUE,
  rule_name VARCHAR2(200) NOT NULL,
  rule_type VARCHAR2(40) NOT NULL,
  priority NUMBER(6) NOT NULL,
  is_enabled NUMBER(1) DEFAULT 1 NOT NULL,
  config_json CLOB CHECK (config_json IS JSON),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_matching_rules_enabled CHECK (is_enabled IN (0,1)),
  CONSTRAINT ck_matching_rules_type CHECK (rule_type IN ('deterministic','probabilistic','safety'))
);

CREATE TABLE survivorship_rules (
  survivorship_rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_code VARCHAR2(100) NOT NULL UNIQUE,
  field_name VARCHAR2(100) NOT NULL,
  strategy VARCHAR2(50) NOT NULL,
  priority NUMBER(6) DEFAULT 100 NOT NULL,
  source_preference VARCHAR2(400),
  config_json CLOB CHECK (config_json IS JSON),
  is_enabled NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_survivorship_enabled CHECK (is_enabled IN (0,1))
);

CREATE TABLE rebatch_jobs (
  rebatch_job_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type VARCHAR2(50) NOT NULL,
  job_status VARCHAR2(30) DEFAULT 'queued' NOT NULL,
  requested_by VARCHAR2(200),
  started_at TIMESTAMP,
  finished_at TIMESTAMP,
  total_records NUMBER,
  processed_records NUMBER,
  config_json CLOB CHECK (config_json IS JSON),
  result_json CLOB CHECK (result_json IS JSON),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_rebatch_status CHECK (job_status IN ('queued','running','completed','failed','cancelled'))
);

CREATE INDEX idx_source_records_pk ON source_records (source_pk);
CREATE INDEX idx_norm_email ON normalized_identities (normalized_email);
CREATE INDEX idx_norm_phone ON normalized_identities (normalized_phone);
CREATE INDEX idx_norm_name ON normalized_identities (normalized_name);
CREATE INDEX idx_golden_email ON golden_records (canonical_email);
CREATE INDEX idx_golden_phone ON golden_records (canonical_phone);
CREATE INDEX idx_golden_hkid ON golden_records (canonical_hkid);
CREATE INDEX idx_record_links_source ON record_links (source_record_id);
CREATE INDEX idx_record_links_golden ON record_links (golden_id);
CREATE INDEX idx_match_candidates_source ON match_candidates (source_record_id, confidence DESC);
CREATE INDEX idx_match_features_candidate ON match_candidate_features (match_candidate_id);
CREATE INDEX idx_manual_review_status ON manual_review_tasks (task_status, created_at);
CREATE INDEX idx_merge_history_time ON merge_history (event_at);
CREATE INDEX idx_rebatch_status ON rebatch_jobs (job_status, created_at);

INSERT INTO source_systems (source_code, source_name, trust_level, is_internal)
VALUES ('HR', 'Human Resources', 'high', 1);
INSERT INTO source_systems (source_code, source_name, trust_level, is_internal)
VALUES ('SIS', 'Student Information System', 'high', 1);
INSERT INTO source_systems (source_code, source_name, trust_level, is_internal)
VALUES ('ALUMNI', 'Alumni Office', 'high', 1);
INSERT INTO source_systems (source_code, source_name, trust_level, is_internal)
VALUES ('CRM', 'CRM Platform', 'medium', 0);
INSERT INTO source_systems (source_code, source_name, trust_level, is_internal)
VALUES ('THIRDPARTY', 'Third-Party Event Partner', 'low', 0);

INSERT INTO matching_rules (rule_code, rule_name, rule_type, priority, config_json)
VALUES ('TIER1_INTERNAL_EXACT', 'Trusted internal Tier 1 exact match', 'deterministic', 100,
  '{"source_types":["internal","hr","sis","student","alumni"],"required":["tier1_exact"],"decision":"auto-merge"}');
INSERT INTO matching_rules (rule_code, rule_name, rule_type, priority, config_json)
VALUES ('TIER1_THIRDPARTY_SUPPORT', 'Third-party Tier 1 exact needs supporting evidence', 'deterministic', 95,
  '{"source_types":["third_party","thirdparty","crm"],"required":["tier1_exact","supporting_evidence"],"decision":"auto-merge"}');
INSERT INTO matching_rules (rule_code, rule_name, rule_type, priority, config_json)
VALUES ('TIER1_CONFLICT_BLOCK', 'Tier 1 conflict blocks auto-merge', 'safety', 99,
  '{"check":["hkid","emplid","student_id","alumni_id"],"action":"manual-review"}');
INSERT INTO matching_rules (rule_code, rule_name, rule_type, priority, config_json)
VALUES ('MULTI_HIGH_CANDIDATE', 'Multiple high confidence candidates trigger review', 'safety', 80,
  '{"high_threshold":0.85,"min_count":2,"action":"manual-review"}');
INSERT INTO matching_rules (rule_code, rule_name, rule_type, priority, config_json)
VALUES ('LOW_SCORE_GAP', 'Low top-two score gap triggers review', 'safety', 75,
  '{"score_gap_threshold":0.10,"action":"manual-review"}');

INSERT INTO survivorship_rules (rule_code, field_name, strategy, priority, source_preference, config_json)
VALUES ('SURV_TIER1_TRUST', 'canonical_hkid', 'trust_best_source', 100, 'HR,SIS,ALUMNI,CRM,THIRDPARTY',
  '{"trusted_sources":["HR","SIS","ALUMNI"]}');
INSERT INTO survivorship_rules (rule_code, field_name, strategy, priority, source_preference, config_json)
VALUES ('SURV_EMAIL_VERIFIED', 'canonical_email', 'most_recent_non_null', 90, 'HR,SIS,ALUMNI,CRM,THIRDPARTY',
  '{"prefer_verified":true}');
INSERT INTO survivorship_rules (rule_code, field_name, strategy, priority, source_preference, config_json)
VALUES ('SURV_PHONE_RECENT', 'canonical_phone', 'most_recent_non_null', 80, 'HR,SIS,ALUMNI,CRM,THIRDPARTY',
  '{"allow_last7":true}');
INSERT INTO survivorship_rules (rule_code, field_name, strategy, priority, source_preference, config_json)
VALUES ('SURV_NAME_COMPLETE', 'canonical_name', 'most_complete', 70, 'HR,SIS,ALUMNI,CRM,THIRDPARTY',
  '{"min_length":3}');
INSERT INTO survivorship_rules (rule_code, field_name, strategy, priority, source_preference, config_json)
VALUES ('SURV_ADDRESS_RECENT', 'canonical_address', 'most_recent_non_null', 60, 'HR,SIS,ALUMNI,CRM,THIRDPARTY',
  '{"normalize_whitespace":true}');

COMMIT;
