-- Oracle schema for Identity Resolution Engine (IRE)
-- Creates source_records, golden_records, record_links, manual_review_queue, merge_history
-- Use a dedicated schema/user for IRE (recommended).

-- 1) Create tables
CREATE TABLE source_records (
  source_record_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_name        VARCHAR2(100) NOT NULL, -- e.g., HR, SIS, CRM, ThirdParty
  source_pk          VARCHAR2(200) NOT NULL, -- original primary key in source
  raw_payload        CLOB,                    -- raw JSON payload
  normalized_name    VARCHAR2(4000),
  normalized_email   VARCHAR2(320),
  normalized_phone   VARCHAR2(50),
  hkid               VARCHAR2(50),
  emplid             VARCHAR2(50),
  studentid          VARCHAR2(50),
  alumniid           VARCHAR2(50),
  address            VARCHAR2(2000),
  ingest_ts          TIMESTAMP DEFAULT SYSTIMESTAMP,
  ingest_user        VARCHAR2(100)
);

CREATE TABLE golden_records (
  golden_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_name     VARCHAR2(4000),
  canonical_email    VARCHAR2(320),
  canonical_phone    VARCHAR2(50),
  canonical_hkid     VARCHAR2(50),
  canonical_emplid   VARCHAR2(50),
  canonical_studentid VARCHAR2(50),
  canonical_alumniid VARCHAR2(50),
  canonical_address  VARCHAR2(2000),
  provenance         CLOB, -- JSON describing field-level provenance
  last_updated       TIMESTAMP DEFAULT SYSTIMESTAMP,
  status             VARCHAR2(50) DEFAULT 'active'
);

CREATE TABLE record_links (
  link_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id   NUMBER NOT NULL,
  golden_id          NUMBER NOT NULL,
  link_confidence    NUMBER(5,4) NOT NULL, -- 0.0000 - 1.0000
  link_method        VARCHAR2(50), -- 'deterministic'|'probabilistic'|'manual'
  evidence           CLOB,
  link_ts            TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_rl_src_rec FOREIGN KEY (source_record_id) REFERENCES source_records(source_record_id),
  CONSTRAINT fk_rl_golden FOREIGN KEY (golden_id) REFERENCES golden_records(golden_id)
);

CREATE TABLE manual_review_queue (
  task_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_record_id   NUMBER NOT NULL,
  candidate_goldens  VARCHAR2(2000), -- comma-separated golden_ids OR JSON list
  best_confidence    NUMBER(5,4),
  status             VARCHAR2(50) DEFAULT 'open', -- open|assigned|resolved
  assigned_to        VARCHAR2(100),
  created_ts         TIMESTAMP DEFAULT SYSTIMESTAMP,
  resolved_ts        TIMESTAMP,
  reviewer_decision  VARCHAR2(50),
  notes              CLOB,
  CONSTRAINT fk_mrq_src_rec FOREIGN KEY (source_record_id) REFERENCES source_records(source_record_id)
);

CREATE TABLE merge_history (
  event_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type         VARCHAR2(50), -- 'merge'|'split'|'update'|'link'
  actor              VARCHAR2(100), -- 'system' or reviewer name/id
  details            CLOB,
  event_ts           TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 2) Sample seed data (a few source records + 1 golden)
INSERT INTO golden_records (canonical_name, canonical_email, canonical_phone, canonical_hkid, canonical_emplid, provenance)
VALUES ('John Michael Smith', 'jsmith@ust.hk', '+8525551234567', 'A123456(7)', 'E1001',
        '{"name":{"source":"HR","source_pk":"1001","reason":"trusted_source"},"email":{"source":"SIS","reason":"most_recent"}}');

INSERT INTO golden_records (canonical_name, canonical_email, canonical_phone, canonical_hkid, canonical_emplid, provenance)
VALUES ('Jane Chan', 'jchan@example.com', '+85291234567', NULL, 'E2002',
        '{"name":{"source":"HR","reason":"best_source"}}');

COMMIT;

INSERT INTO source_records (source_name, source_pk, raw_payload, normalized_name, normalized_email, normalized_phone, hkid, emplid, studentid, alumniid, address, ingest_user)
VALUES ('HR', '1001', '{"name":"John M. Smith","email":"jsmith@ust.hk","phone":"+852-555-123-4567","hkid":"A123456(7)"}',
        'John M. Smith', 'jsmith@ust.hk', '+8525551234567', 'A123456(7)', 'E1001', NULL, NULL, 'Clear Water Bay', 'ingest_service');

INSERT INTO source_records (source_name, source_pk, raw_payload, normalized_name, normalized_email, normalized_phone, hkid, emplid, studentid, alumniid, address, ingest_user)
VALUES ('SIS', 'S100', '{"name":"John Smith","email":"jsmith@ust.hk","phone":"555-123-4567"}',
        'John Smith', 'jsmith@ust.hk', '5551234567', NULL, NULL, 'S100', NULL, 'Clear Water Bay', 'ingest_service');

INSERT INTO source_records (source_name, source_pk, raw_payload, normalized_name, normalized_email, normalized_phone, hkid, emplid, studentid, alumniid, address, ingest_user)
VALUES ('ThirdParty', 'TP_900', '{"name":"John Smith","email":"jsmith+spam@ust.hk","phone":"(852)5551234567"}',
        'John Smith', 'jsmith+spam@ust.hk', '+8525551234567', NULL, NULL, NULL, NULL, 'Clear Water Bay', 'thirdparty_sync');

COMMIT;

-- 3) Example queries: candidate generation (blocking), similarity, create match candidate rows
-- A) Exact-match blocking by email
SELECT sr.source_record_id, gr.golden_id, 'email' as block_on
FROM source_records sr
JOIN golden_records gr ON LOWER(sr.normalized_email) = LOWER(gr.canonical_email)
WHERE sr.normalized_email IS NOT NULL;

-- B) Exact-match blocking by phone (norm stripping non-digit characters expected at ingest)
SELECT sr.source_record_id, gr.golden_id, 'phone' as block_on
FROM source_records sr
JOIN golden_records gr ON REGEXP_REPLACE(sr.normalized_phone,'\D') = REGEXP_REPLACE(gr.canonical_phone,'\D')
WHERE sr.normalized_phone IS NOT NULL;

-- C) Name similarity (using UTL_MATCH EDIT_DISTANCE_SIMILARITY which returns 0-100)
SELECT sr.source_record_id, gr.golden_id,
       UTL_MATCH.EDIT_DISTANCE_SIMILARITY(sr.normalized_name, gr.canonical_name)/100 AS name_sim
FROM source_records sr
CROSS JOIN golden_records gr
WHERE sr.normalized_name IS NOT NULL
  AND UTL_MATCH.EDIT_DISTANCE_SIMILARITY(sr.normalized_name, gr.canonical_name) >= 70; -- threshold 70%

-- D) Assemble candidate scores (example with weights applied in query)
-- Suppose priorities: name=40, email=80, phone=60, id=100 (only present fields considered)
-- For demo, compute dynamic weights per row using DECODE to check present fields
SELECT
  sr.source_record_id,
  gr.golden_id,
  CASE WHEN sr.normalized_name IS NOT NULL THEN UTL_MATCH.EDIT_DISTANCE_SIMILARITY(sr.normalized_name, gr.canonical_name)/100 ELSE NULL END AS sim_name,
  CASE WHEN sr.normalized_email IS NOT NULL THEN CASE WHEN LOWER(sr.normalized_email)=LOWER(gr.canonical_email) THEN 1 ELSE 0 END ELSE NULL END AS sim_email,
  CASE WHEN sr.normalized_phone IS NOT NULL THEN CASE WHEN REGEXP_REPLACE(sr.normalized_phone,'\D')=REGEXP_REPLACE(gr.canonical_phone,'\D') THEN 1 ELSE 0 END ELSE NULL END AS sim_phone,
  -- dynamic weights calculation (simplified) 
  -- present_priority_sum = sum of priorities for non-null fields
  -- weight_name = 40/present_priority_sum etc.
  40/( (CASE WHEN sr.normalized_name IS NOT NULL THEN 40 ELSE 0 END) + (CASE WHEN sr.normalized_email IS NOT NULL THEN 80 ELSE 0 END) + (CASE WHEN sr.normalized_phone IS NOT NULL THEN 60 ELSE 0 END) + (CASE WHEN sr.hkid IS NOT NULL THEN 100 ELSE 0 END) ) AS weight_name,
  80/( (CASE WHEN sr.normalized_name IS NOT NULL THEN 40 ELSE 0 END) + (CASE WHEN sr.normalized_email IS NOT NULL THEN 80 ELSE 0 END) + (CASE WHEN sr.normalized_phone IS NOT NULL THEN 60 ELSE 0 END) + (CASE WHEN sr.hkid IS NOT NULL THEN 100 ELSE 0 END) ) AS weight_email,
  60/( (CASE WHEN sr.normalized_name IS NOT NULL THEN 40 ELSE 0 END) + (CASE WHEN sr.normalized_email IS NOT NULL THEN 80 ELSE 0 END) + (CASE WHEN sr.normalized_phone IS NOT NULL THEN 60 ELSE 0 END) + (CASE WHEN sr.hkid IS NOT NULL THEN 100 ELSE 0 END) ) AS weight_phone
FROM source_records sr
CROSS JOIN golden_records gr
WHERE sr.source_record_id = :IN_SRC_REC_ID; -- bind param for incoming source_record_id

-- E) Insert a link after auto-merge (example)
INSERT INTO record_links (source_record_id, golden_id, link_confidence, link_method, evidence)
VALUES (:src_rec_id, :golden_id, :confidence, 'probabilistic', '{"sims":{"name":0.94,"email":1.0,"phone":1.0}}');

COMMIT;
